/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as EntradasRouteImport } from './routes/entradas'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RetiradasRouteImport } from './routes/retiradas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EntradasRoute = EntradasRouteImport.update({
  id: '/entradas',
  path: '/entradas',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RetiradasRoute = RetiradasRouteImport.update({
  id: '/retiradas',
  path: '/retiradas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compras': typeof ComprasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/entradas': typeof EntradasRoute
  '/estoque': typeof EstoqueRoute
  '/inventario': typeof InventarioRoute
  '/relatorios': typeof RelatoriosRoute
  '/retiradas': typeof RetiradasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compras': typeof ComprasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/entradas': typeof EntradasRoute
  '/estoque': typeof EstoqueRoute
  '/inventario': typeof InventarioRoute
  '/relatorios': typeof RelatoriosRoute
  '/retiradas': typeof RetiradasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compras': typeof ComprasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/entradas': typeof EntradasRoute
  '/estoque': typeof EstoqueRoute
  '/inventario': typeof InventarioRoute
  '/relatorios': typeof RelatoriosRoute
  '/retiradas': typeof RetiradasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compras'
    | '/configuracoes'
    | '/entradas'
    | '/estoque'
    | '/inventario'
    | '/relatorios'
    | '/retiradas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compras'
    | '/configuracoes'
    | '/entradas'
    | '/estoque'
    | '/inventario'
    | '/relatorios'
    | '/retiradas'
  id:
    | '__root__'
    | '/'
    | '/compras'
    | '/configuracoes'
    | '/entradas'
    | '/estoque'
    | '/inventario'
    | '/relatorios'
    | '/retiradas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComprasRoute: typeof ComprasRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EntradasRoute: typeof EntradasRoute
  EstoqueRoute: typeof EstoqueRoute
  InventarioRoute: typeof InventarioRoute
  RelatoriosRoute: typeof RelatoriosRoute
  RetiradasRoute: typeof RetiradasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entradas': {
      id: '/entradas'
      path: '/entradas'
      fullPath: '/entradas'
      preLoaderRoute: typeof EntradasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retiradas': {
      id: '/retiradas'
      path: '/retiradas'
      fullPath: '/retiradas'
      preLoaderRoute: typeof RetiradasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComprasRoute: ComprasRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EntradasRoute: EntradasRoute,
  EstoqueRoute: EstoqueRoute,
  InventarioRoute: InventarioRoute,
  RelatoriosRoute: RelatoriosRoute,
  RetiradasRoute: RetiradasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}